{{- if not .Values.communications.existingSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube-router.CommunicationsSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "botkube-router.name" . }}
    helm.sh/chart: {{ include "botkube-router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  comm_router_config.yaml: |
    # Communication settings
    communications:
      {{- with .Values.communications }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
