apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "botkube-router.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "botkube-router.name" . }}
    helm.sh/chart: {{ include "botkube-router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  cache_router.yaml: |
  {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
  {{- end }}