{{ if .Values.ingress.create }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ include "botkube-router.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "botkube-router.name" . }}
    helm.sh/chart: {{ include "botkube-router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.communications.lark.messagePath }}
            backend:
              serviceName: {{ include "botkube-router.fullname" . }}
              servicePort: {{ .Values.communications.lark.port }}
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
  {{- end }}