apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "botkube-router.serviceAccountName" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "botkube-router.name" . }}
    helm.sh/chart: {{ include "botkube-router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
