issues:
  exclude-use-default: false
  exclude:
    # Read more: https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope `tc` in function literal
    # EXC0001 errcheck: source: https://github.com/kubernetes-sigs/controller-runtime/blob/master/.golangci.yml#L94
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    # EXC0008 gosec: Duplicated errcheck checks
    - (G104|G307)
run:
  tests: true
  build-tags:
    - integration
  skip-files:
    - ".*\\.generated\\.go$"
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - misspell
    - gochecknoinits
    - unparam
    - exportloopref
    - gosec
    - goimports
    - whitespace
    - bodyclose
    - gocyclo

  fast: false
linters-settings:
  goimports:
  # put imports beginning with prefix after 3rd-party packages;
  # it's a comma-separated list of prefixes
  local-prefixes: github.com/kubeshop/botkube
  gocyclo:
    # https://github.com/kubeshop/botkube/issues/745
    min-complexity: 45
  revive:
    rules:
      # Disable warns about capitalized and ended with punctuation error messages
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings
      - name: error-strings
        disabled: true
