project_name: botkube
env:
  - IMAGE_REGISTRY={{ if index .Env "IMAGE_REGISTRY"  }}{{ .Env.IMAGE_REGISTRY }}{{ else }}ghcr.io{{ end }}
  - IMAGE_REPOSITORY={{ if index .Env "IMAGE_REPOSITORY"  }}{{ .Env.IMAGE_REPOSITORY }}{{ else }}kubeshop/botkube{{ end }}
  - IMAGE_TAG={{ if index .Env "IMAGE_TAG"  }}{{ .Env.IMAGE_TAG }}{{ else }}{{ .Tag }}{{ end }}
  - ANALYTICS_API_KEY={{ if index .Env "ANALYTICS_API_KEY"  }}{{ .Env.ANALYTICS_API_KEY }}{{ else }}{{ end }}
before:
  hooks:
    - go mod download
builds:
  - id: botkube
    binary: botkube
    main: cmd/botkube/main.go
    ldflags: &ldflags
      - -s -w
        -X github.com/kubeshop/botkube/pkg/version.Version={{ .Env.IMAGE_TAG }}
        -X github.com/kubeshop/botkube/pkg/version.GitCommitID={{ .Commit }}
        -X github.com/kubeshop/botkube/pkg/version.BuildDate={{ .Date }}
        -X github.com/kubeshop/botkube/internal/analytics.APIKey={{ .Env.ANALYTICS_API_KEY }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  - id: my-archive
    builds:
      - botkube
snapshot:
  name_template: "{{ .Env.IMAGE_TAG }}"
release:
  # If set to true, will not auto-publish the release.
  draft: true
  prerelease: auto
  ids:
    - botkube
changelog:
  skip: true

dockers:
  - image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Env.IMAGE_TAG }}-amd64"
    use: buildx
    dockerfile: "build/Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=botkube_version={{ .Env.IMAGE_TAG }}"
  - image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Env.IMAGE_TAG }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: "build/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=botkube_version={{ .Env.IMAGE_TAG }}"
  - image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Env.IMAGE_TAG }}-armv7"
    use: buildx
    goarch: arm
    goarm: 7
    dockerfile: "build/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm"
      - "--build-arg=botkube_version={{ .Env.IMAGE_TAG }}"
docker_manifests:
  - name_template: "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Env.IMAGE_TAG }}"
    image_templates:
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Env.IMAGE_TAG }}-amd64"
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Env.IMAGE_TAG }}-arm64"
      - "{{.Env.IMAGE_REGISTRY}}/{{.Env.IMAGE_REPOSITORY}}:{{ .Env.IMAGE_TAG }}-armv7"
