pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=develop
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - label!=hold-off-merging
      - check-success=Build app
      - check-success=Lint Helm chart
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} #{{ number }}
          {{ body }}
