package commplatform

import (
	"regexp"

	"github.com/sanity-io/litter"
)

// structDumper provides an option to print the struct in more readable way.
var structDumper = litter.Options{
	HidePrivateFields: true,
	HideZeroValues:    true,
	StripPackageNames: false,
	FieldExclusions:   regexp.MustCompile(`^(XXX_.*)$`), // XXX_ is a prefix of fields generated by protoc-gen-go
	Separator:         " ",
}
