// Package model contains copied GraphQL models generated by gqlgen for Botkube Cloud GraphQL API.
// Apart from the generated `models_gen.go` file, other files contain copied, customized models.
package model
