apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-svcs
  namespace: default
subjects:
  - kind: Group
    name: rbac-test
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: svc-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: svc-reader
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
