{{- if not .Values.existingCommunicationsSecretName -}}
{{- $secretName := printf "%s-%s" (include "botkube.fullname" .) "communication-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube.CommunicationsSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{- $previous := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if $previous }}
  comm_config.yaml: |
    {{- $prev := b64dec (index $previous.data "comm_config.yaml") -}}
    {{- $prevYaml := $prev | fromYaml -}}
    {{- $merged := mustMergeOverwrite (mustDeepCopy (default (dict) $prevYaml.communications )) (mustDeepCopy .Values.communications) }}
    communications:
      {{ $merged | toYaml | indent 8 -}}
  {{- else }}
  comm_config.yaml: |
    # Communication settings
    communications:
      {{- .Values.communications | toYaml | nindent 6 }}
  {{ end }}
{{- end }}
