// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: cloud_teams.proto

package cloudteams

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_EXECUTOR MessageType = 0
	MessageType_MESSAGE_SOURCE   MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_EXECUTOR",
		1: "MESSAGE_SOURCE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_EXECUTOR": 0,
		"MESSAGE_SOURCE":   1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_teams_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_cloud_teams_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_cloud_teams_proto_rawDescGZIP(), []int{0}
}

type AgentActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// message sent by agent, either as a response to a command or an event from enabled sources
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AgentActivity) Reset() {
	*x = AgentActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_teams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentActivity) ProtoMessage() {}

func (x *AgentActivity) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_teams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentActivity.ProtoReflect.Descriptor instead.
func (*AgentActivity) Descriptor() ([]byte, []int) {
	return file_cloud_teams_proto_rawDescGZIP(), []int{0}
}

func (x *AgentActivity) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId         string      `protobuf:"bytes,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	ActivityId     string      `protobuf:"bytes,2,opt,name=activityId,proto3" json:"activityId,omitempty"`
	ConversationId string      `protobuf:"bytes,3,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	MessageType    MessageType `protobuf:"varint,4,opt,name=messageType,proto3,enum=cloudteams.MessageType" json:"messageType,omitempty"`
	Data           []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_teams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_teams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cloud_teams_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Message) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_EXECUTOR
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CloudActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event                   []byte `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	ConversationDisplayName string `protobuf:"bytes,2,opt,name=conversationDisplayName,proto3" json:"conversationDisplayName,omitempty"`
}

func (x *CloudActivity) Reset() {
	*x = CloudActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_teams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudActivity) ProtoMessage() {}

func (x *CloudActivity) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_teams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudActivity.ProtoReflect.Descriptor instead.
func (*CloudActivity) Descriptor() ([]byte, []int) {
	return file_cloud_teams_proto_rawDescGZIP(), []int{2}
}

func (x *CloudActivity) GetEvent() []byte {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CloudActivity) GetConversationDisplayName() string {
	if x != nil {
		return x.ConversationDisplayName
	}
	return ""
}

var File_cloud_teams_proto protoreflect.FileDescriptor

var file_cloud_teams_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x22,
	0x3e, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0xb8, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61,
	0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5f, 0x0a, 0x0d, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x38, 0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x17, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x37, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x4f, 0x55, 0x52,
	0x43, 0x45, 0x10, 0x01, 0x32, 0x5a, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x54, 0x65, 0x61,
	0x6d, 0x73, 0x12, 0x4c, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x12, 0x19, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x74, 0x65, 0x61, 0x6d,
	0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x1a,
	0x19, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_teams_proto_rawDescOnce sync.Once
	file_cloud_teams_proto_rawDescData = file_cloud_teams_proto_rawDesc
)

func file_cloud_teams_proto_rawDescGZIP() []byte {
	file_cloud_teams_proto_rawDescOnce.Do(func() {
		file_cloud_teams_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_teams_proto_rawDescData)
	})
	return file_cloud_teams_proto_rawDescData
}

var file_cloud_teams_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cloud_teams_proto_goTypes = []interface{}{
	(MessageType)(0),      // 0: cloudteams.MessageType
	(*AgentActivity)(nil), // 1: cloudteams.AgentActivity
	(*Message)(nil),       // 2: cloudteams.Message
	(*CloudActivity)(nil), // 3: cloudteams.CloudActivity
}
var file_cloud_teams_proto_depIdxs = []int32{
	2, // 0: cloudteams.AgentActivity.message:type_name -> cloudteams.Message
	0, // 1: cloudteams.Message.messageType:type_name -> cloudteams.MessageType
	1, // 2: cloudteams.CloudTeams.StreamActivity:input_type -> cloudteams.AgentActivity
	3, // 3: cloudteams.CloudTeams.StreamActivity:output_type -> cloudteams.CloudActivity
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cloud_teams_proto_init() }
func file_cloud_teams_proto_init() {
	if File_cloud_teams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_teams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_teams_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_teams_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_teams_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_teams_proto_goTypes,
		DependencyIndexes: file_cloud_teams_proto_depIdxs,
		EnumInfos:         file_cloud_teams_proto_enumTypes,
		MessageInfos:      file_cloud_teams_proto_msgTypes,
	}.Build()
	File_cloud_teams_proto = out.File
	file_cloud_teams_proto_rawDesc = nil
	file_cloud_teams_proto_goTypes = nil
	file_cloud_teams_proto_depIdxs = nil
}
