{{- if not .Values.communications.existingSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube.CommunicationsSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  comm_config.yaml: |
    # Communication settings
    communications:
      {{- with .Values.communications }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
