{{- if not .Values.existingCommunicationsSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube.CommunicationsSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    botkube.io/config-watch: "true"
stringData:
  comm_config.yaml: |
    # Communication settings
    communications:
      {{- .Values.communications | toYaml | nindent 6 }}
{{- end }}
