{{ $groupsToCreate := .Values.rbac.groups }}
{{- if .Values.rbac.staticGroupName }}
{{ $defaultGroup := dict "rules" .Values.rbac.rules "create" .Values.rbac.create }}
{{ $_ := set $groupsToCreate .Values.rbac.staticGroupName $defaultGroup }}
{{- end }}

{{- range $name, $value := $groupsToCreate }}
{{- if $value.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" $ }}
    helm.sh/chart: {{ include "botkube.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
rules:
{{- with $value.rules }}
{{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" $ }}
    helm.sh/chart: {{ include "botkube.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
subjects:
  - kind: Group
    name: {{ $name }}
    apiGroup: rbac.authorization.k8s.io
---
{{ end }}
{{- end }}
