{{- if or .Values.serviceMonitor.enabled (include "botkube.communication.team.enabled" $) (.Values.settings.lifecycleServer.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "botkube.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: botkube
spec:
  type: ClusterIP
  ports:
  {{- if .Values.settings.lifecycleServer.enabled }}
  - name: "lifecycle"
    port: {{ .Values.settings.lifecycleServer.port }}
    targetPort: {{ .Values.settings.lifecycleServer.port }}
  {{- end }}
  {{- if .Values.serviceMonitor.enabled }}
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  {{- end }}
  {{- range $key, $val := .Values.communications }}
  {{- if .teams.enabled }}
  - name: {{ $key | quote }}
    port: {{ $val.teams.port }}
  {{- end }}
  {{- end }}
  selector:
    app: botkube
{{- end }}
