---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-1671535722
  namespace: "test2"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.5
    app.kubernetes.io/instance: postgresql-1671535722
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "Tm1HMXBmNmVNSQ=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
