name: Helm chart testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run chart lint & helm-docs
        run: make process-chart

      - name: Detect git changes
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '❌ \033[0;31mHelm documentation outdated. Run 'make process-chart'.\033[0m'
            git diff --color
            exit 1
          else
            echo '✔ No issues detected. Have a nice day :-)'
          fi
