name: Botkube Cloud Prod E2E test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours

env:
  HELM_VERSION: v3.9.0
  K3D_VERSION: v5.4.6
  GIT_USER: botkube-dev

jobs:
  cloud-slack-prod-e2e:
    name: Botkube Cloud Slack Prod E2E
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    concurrency:
      group: cloud-slack-prod-e2e
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run e2e tests
        uses: ./.github/actions/cloud-slack-e2e
        with:
          access_token: ${{ secrets.E2E_TEST_GH_DEV_ACCOUNT_PAT }}
          
          slack_workspace_name: ${{ secrets.E2E_DEV_SLACK_WORKSPACE_NAME }}
          slack_email: ${{ secrets.E2E_DEV_SLACK_EMAIL }}
          slack_password: ${{ secrets.E2E_DEV_SLACK_USER_PASSWORD }}
          slack_bot_display_name: "Botkube"
          slack_tester_bot_token: ${{ secrets.E2E_DEV_SLACK_TESTER_BOT_TOKEN }}
          slack_tester_bot_name: "botkube3"
          
          botkube_cloud_api_base_url: "https://api.botkube.io"
          botkube_cloud_email: ${{ secrets.E2E_DEV_BOTKUBE_CLOUD_EMAIL }}
          botkube_cloud_password: ${{ secrets.E2E_DEV_BOTKUBE_CLOUD_PASSWORD }}
          botkube_cloud_team_organization_id: ${{ secrets.E2E_PROD_BOTKUBE_CLOUD_TEAM_ORGANIZATION_ID }}

          slack_alerts_webhook: ${{ secrets.SLACK_CI_ALERTS_WEBHOOK }}

          e2e_type: "PROD"
